import type { MusicItem, VideoItem, ActivityItem } from './contentData';

// Massive expanded music database (500+ songs across all emotions)
export const musicDatabase: Record<string, MusicItem[]> = {
  happy: [
    { title: 'Happy', artist: 'Pharrell Williams', youtubeId: 'ZbZSe6N_BXs' },
    { title: "Don't Stop Me Now", artist: 'Queen', youtubeId: 'HgzGwKwLmgM' },
    { title: 'Walking on Sunshine', artist: 'Katrina and the Waves', youtubeId: 'iPUmE-tne5U' },
    { title: 'Good Vibrations', artist: 'The Beach Boys', youtubeId: 'Eab_beh07HU' },
    { title: 'September', artist: 'Earth, Wind & Fire', youtubeId: 'Gs069dndIYk' },
    { title: 'I Got a Feeling', artist: 'Black Eyed Peas', youtubeId: 'uSD4vsh1zDA' },
    { title: 'Lovely Day', artist: 'Bill Withers', youtubeId: 'bEeaS6fuUoA' },
    { title: 'Mr. Blue Sky', artist: 'Electric Light Orchestra', youtubeId: 'aQUlA8Hcv4s' },
    { title: 'Best Day of My Life', artist: 'American Authors', youtubeId: 'Y66j_BUCBMY' },
    { title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars', youtubeId: 'OPf0YbXqDm0' },
    { title: 'Can\'t Stop the Feeling', artist: 'Justin Timberlake', youtubeId: 'ru0K8uYEZWw' },
    { title: 'Good as Hell', artist: 'Lizzo', youtubeId: 'SmbmeOgWsqE' },
    { title: 'Shake It Off', artist: 'Taylor Swift', youtubeId: 'nfWlot6h_JM' },
    { title: 'Dancing Queen', artist: 'ABBA', youtubeId: 'xFrGuyw1V8s' },
    { title: 'I Want to Break Free', artist: 'Queen', youtubeId: 'f4Mc-NYPHaQ' },
    { title: 'Dynamite', artist: 'BTS', youtubeId: 'gdZLi9oWNZg' },
    { title: 'Sugar', artist: 'Maroon 5', youtubeId: '09R8_2nJtjg' },
    { title: 'Treasure', artist: 'Bruno Mars', youtubeId: 'nPvuNsRccVw' },
    { title: 'Electric Feel', artist: 'MGMT', youtubeId: 'MmZexg8sxyk' },
    { title: 'Pharrell - Freedom', artist: 'Pharrell Williams', youtubeId: 'LBKLvsFZHJw' }
  ],
  
  excited: [
    { title: 'Eye of the Tiger', artist: 'Survivor', youtubeId: 'btPJPFnesV4' },
    { title: 'Till I Collapse', artist: 'Eminem', youtubeId: 'ytQ5CYE1VZw' },
    { title: "Can't Stop", artist: 'Red Hot Chili Peppers', youtubeId: 'BfOdWSiyWoc' },
    { title: 'Levels', artist: 'Avicii', youtubeId: '_ovdm2yX4MA' },
    { title: 'Thunderstruck', artist: 'AC/DC', youtubeId: 'v2AC41dglnM' },
    { title: 'We Will Rock You', artist: 'Queen', youtubeId: '-tJYN-eG1zk' },
    { title: 'Lose Yourself', artist: 'Eminem', youtubeId: '_Yhyp-_hX2s' },
    { title: 'Pump It', artist: 'Black Eyed Peas', youtubeId: 'ZaI2IlHwmgQ' },
    { title: 'Started From the Bottom', artist: 'Drake', youtubeId: 'RubBzkZzpUA' },
    { title: 'Remember the Name', artist: 'Fort Minor', youtubeId: 'VDvr08sCPOc' },
    { title: 'Can\'t Hold Us', artist: 'Macklemore & Ryan Lewis', youtubeId: '2zNSgSzhBfM' },
    { title: 'Bring Em Out', artist: 'T.I.', youtubeId: 'dVDk7PXNXB8' },
    { title: 'Turn Down for What', artist: 'DJ Snake & Lil Jon', youtubeId: 'HMUDVMiITOU' },
    { title: 'Animals', artist: 'Martin Garrix', youtubeId: 'gCYcHz2k5x0' },
    { title: 'Titanium', artist: 'David Guetta ft. Sia', youtubeId: 'JRfuAukYTKg' },
    { title: 'Wake Me Up', artist: 'Avicii', youtubeId: 'IcrbM1l_BoI' },
    { title: 'Feel So Close', artist: 'Calvin Harris', youtubeId: 'dGghkjpNCQ8' },
    { title: 'Don\'t You Worry Child', artist: 'Swedish House Mafia', youtubeId: '1y6smkh6c-0' },
    { title: 'Spaceman', artist: 'Hardwell', youtubeId: 'AwVq2qsqOHg' },
    { title: 'Epic', artist: '2WEI', youtubeId: 'wVNAHTwuPew' }
  ],
  
  grateful: [
    { title: 'What a Wonderful World', artist: 'Louis Armstrong', youtubeId: 'VqhCQZaH4Vs' },
    { title: 'Thank You', artist: 'Dido', youtubeId: '1TO48Cnl66w' },
    { title: 'Count on Me', artist: 'Bruno Mars', youtubeId: 'fLexgOxsZu0' },
    { title: 'Three Little Birds', artist: 'Bob Marley', youtubeId: 'zaGUr6wzyT8' },
    { title: 'Blessings', artist: 'Chance the Rapper', youtubeId: 'p6eCOhvxxJw' },
    { title: 'Grateful', artist: 'Rita Ora', youtubeId: 'BreI4RqVDlg' },
    { title: 'I Lived', artist: 'OneRepublic', youtubeId: 'z0rxydSolwU' },
    { title: 'Thank God', artist: 'Kane Brown', youtubeId: 'z6r9IaXTfHU' },
    { title: 'God Gave Me You', artist: 'Blake Shelton', youtubeId: 'h0f5lFXQJWc' },
    { title: 'Thankful', artist: 'Josh Groban', youtubeId: 'LTy3zsNb1Xo' },
    { title: 'Blessed', artist: 'Elton John & John Lennon', youtubeId: 'eFvi7vp7mfI' },
    { title: 'Beautiful Day', artist: 'U2', youtubeId: 'co6WMzDOh1o' },
    { title: 'Somewhere Over the Rainbow', artist: 'Israel Kamakawiwoʻole', youtubeId: 'V1bFr2SWP1I' },
    { title: 'Here Comes the Sun', artist: 'The Beatles', youtubeId: 'KQetemT1sWc' },
    { title: 'Good Life', artist: 'OneRepublic', youtubeId: 'jZhQOvvV45w' },
    { title: 'All You Need Is Love', artist: 'The Beatles', youtubeId: '_7xMfIp-irg' },
    { title: 'Perfect', artist: 'Ed Sheeran', youtubeId: '2Vv-BfVoq4g' },
    { title: 'Just the Way You Are', artist: 'Bruno Mars', youtubeId: 'LjhCEhWiKXk' },
    { title: 'Gratitude', artist: 'Brandon Lake', youtubeId: 'oLDGNPb7AHU' },
    { title: 'Thank You Lord', artist: 'Don Moen', youtubeId: 'tjyAqGN-dOg' }
  ],
  
  confident: [
    { title: 'Stronger', artist: 'Kanye West', youtubeId: 'PsO6ZnUZI0g' },
    { title: 'Roar', artist: 'Katy Perry', youtubeId: 'CevxZvSJLk8' },
    { title: 'Hall of Fame', artist: 'The Script', youtubeId: 'mk48xRzuNvA' },
    { title: 'Confident', artist: 'Demi Lovato', youtubeId: 'cwX9K6bS6HQ' },
    { title: 'Fighter', artist: 'Christina Aguilera', youtubeId: 'PstrAfoMKlc' },
    { title: 'Survivor', artist: 'Destiny\'s Child', youtubeId: 'Wmc8bQoL-J0' },
    { title: 'Run the World (Girls)', artist: 'Beyoncé', youtubeId: 'VBmMU_iwe6U' },
    { title: 'Born This Way', artist: 'Lady Gaga', youtubeId: 'wV1FrqwZyKw' },
    { title: 'Firework', artist: 'Katy Perry', youtubeId: 'QGJuMBdaqIw' },
    { title: 'Brave', artist: 'Sara Bareilles', youtubeId: 'QUQsqBqxoR4' },
    { title: 'This Is Me', artist: 'Keala Settle', youtubeId: 'XLFEvHWD_NE' },
    { title: 'Unstoppable', artist: 'Sia', youtubeId: 'YaEG2aWJnZ8' },
    { title: 'Warrior', artist: 'Demi Lovato', youtubeId: 'Vc5nUUPC5ZM' },
    { title: 'The Champion', artist: 'Carrie Underwood ft. Ludacris', youtubeId: 'bhVmG4HH_14' },
    { title: 'Victory', artist: 'Puff Daddy', youtubeId: 'VHEUFzwIT54' },
    { title: 'All I Do Is Win', artist: 'DJ Khaled', youtubeId: 'GGXzlRoNtHU' },
    { title: 'My Shot', artist: 'Hamilton Cast', youtubeId: 'lIthLJ-Cr_4' },
    { title: 'The Greatest', artist: 'Sia', youtubeId: 'GKSRyLdjsPA' },
    { title: 'Work', artist: 'Rihanna', youtubeId: 'HL1UzIK-flA' },
    { title: 'HUMBLE.', artist: 'Kendrick Lamar', youtubeId: 'tvTRZJ-4EyI' }
  ],
  
  calm: [
    { title: 'Spiegel im Spiegel', artist: 'Arvo Pärt', youtubeId: 'TJ6Mzvh3XCc' },
    { title: 'Music for Airports', artist: 'Brian Eno', youtubeId: 'vNwYtllyt3Q' },
    { title: 'Meditation Music', artist: 'Peaceful Piano', youtubeId: 'lTRiuFIWV54' },
    { title: 'Bamboo Flute', artist: 'Asian Zen', youtubeId: 'KZK6sDZxPuE' },
    { title: 'Weightless', artist: 'Marconi Union', youtubeId: 'UfcAVejslrU' },
    { title: 'Clair de Lune', artist: 'Debussy', youtubeId: 'CvFH_6DNRCY' },
    { title: 'River Flows in You', artist: 'Yiruma', youtubeId: '7maJOI3QMu0' },
    { title: 'Canon in D', artist: 'Pachelbel', youtubeId: 'JvNQLJ1_HQ0' },
    { title: 'Gymnopédie No.1', artist: 'Erik Satie', youtubeId: 'S-Xm7s9eGxU' },
    { title: 'Moonlight Sonata', artist: 'Beethoven', youtubeId: '4Tr0otuiQuU' },
    { title: 'The Blue Danube', artist: 'Johann Strauss II', youtubeId: '_6fAuHNf2u4' },
    { title: 'Nocturne Op.9 No.2', artist: 'Chopin', youtubeId: '9E6b3swbnWg' },
    { title: 'Adagio for Strings', artist: 'Samuel Barber', youtubeId: 'izQsgE0L450' },
    { title: 'Aquarium', artist: 'Saint-Saëns', youtubeId: 'YVpl-RNzdE4' },
    { title: 'Morning Mood', artist: 'Edvard Grieg', youtubeId: 'ImVZPRTjEPc' },
    { title: 'Prelude in C Major', artist: 'Bach', youtubeId: 'PXMVkQ70I88' },
    { title: 'Meditation from Thaïs', artist: 'Massenet', youtubeId: 'mGQLXRTl3Z0' },
    { title: 'Pavane', artist: 'Fauré', youtubeId: 'mpgyTl8yqbw' },
    { title: 'The Lark Ascending', artist: 'Vaughan Williams', youtubeId: 'ZR2JlDnT2l8' },
    { title: 'Sea of Tranquility', artist: 'Liquid Mind', youtubeId: '5KqTp9SvFz4' }
  ],
  
  sad: [
    { title: 'Fix You', artist: 'Coldplay', youtubeId: 'k4V3Mo61fJM' },
    { title: 'The Scientist', artist: 'Coldplay', youtubeId: 'RB-RcX5DS5A' },
    { title: 'Lovely', artist: 'Billie Eilish & Khalid', youtubeId: 'V1Pl8CzNzCw' },
    { title: 'Someone Like You', artist: 'Adele', youtubeId: 'hLQl3WQQoQ0' },
    { title: 'When We Were Young', artist: 'Adele', youtubeId: 'DDWKuo3gXMQ' },
    { title: 'Hello', artist: 'Adele', youtubeId: 'YQHsXMglC9A' },
    { title: 'All of Me', artist: 'John Legend', youtubeId: '450p7goxZqg' },
    { title: 'Say Something', artist: 'A Great Big World', youtubeId: '-2U0Ivkn2Ds' },
    { title: 'Let Her Go', artist: 'Passenger', youtubeId: 'RBumgq5yVrA' },
    { title: 'Stay', artist: 'Rihanna ft. Mikky Ekko', youtubeId: 'JF8BRvqGCNs' },
    { title: 'Skinny Love', artist: 'Bon Iver', youtubeId: 'ssdgFoHLwnk' },
    { title: 'Mad World', artist: 'Gary Jules', youtubeId: '4N3N1MlvVc4' },
    { title: 'Hurt', artist: 'Johnny Cash', youtubeId: '8AHCfZTRGiI' },
    { title: 'The Night We Met', artist: 'Lord Huron', youtubeId: 'KtlgYxa6BMU' },
    { title: 'Tears in Heaven', artist: 'Eric Clapton', youtubeId: 'JxPj3GAYYZ0' },
    { title: 'Nothing Compares 2 U', artist: 'Sinéad O\'Connor', youtubeId: '0-EF60neguk' },
    { title: 'Everybody Hurts', artist: 'R.E.M.', youtubeId: '5rOiW_xY-kc' },
    { title: 'Creep', artist: 'Radiohead', youtubeId: 'XFkzRNyygfk' },
    { title: 'Hallelujah', artist: 'Jeff Buckley', youtubeId: 'y8AWFf7EAc4' },
    { title: 'Black', artist: 'Pearl Jam', youtubeId: 'cs-XZ_dN4Hc' }
  ],
  
  anxious: [
    { title: 'Weightless', artist: 'Marconi Union', youtubeId: 'UfcAVejslrU' },
    { title: 'Clair de Lune', artist: 'Debussy', youtubeId: 'CvFH_6DNRCY' },
    { title: 'Breathe Me', artist: 'Sia', youtubeId: 'SFGvmrJ5rjM' },
    { title: 'River Flows in You', artist: 'Yiruma', youtubeId: '7maJOI3QMu0' },
    { title: 'Zen Garden', artist: 'Meditation Music', youtubeId: 'jNkKDw-aH2U' },
    { title: 'Deep Sleep Music', artist: 'Relaxing Music', youtubeId: 'lFcSrYw-ARY' },
    { title: 'Anxiety Relief', artist: 'Binaural Beats', youtubeId: 'SEfs5TJZ6Nk' },
    { title: 'Calm Piano', artist: 'Peaceful Piano', youtubeId: 'lTRiuFIWV54' },
    { title: 'Ocean Sounds', artist: 'Nature Sounds', youtubeId: 'bn9F19Hi1Lk' },
    { title: 'Rain Sounds', artist: 'Nature Sounds', youtubeId: 'q76bMs-NwRk' },
    { title: 'Forest Ambience', artist: 'Nature Sounds', youtubeId: 'xNN7iTA57jM' },
    { title: 'Tibetan Singing Bowls', artist: 'Meditation Music', youtubeId: 'M0dTJMNZp_4' },
    { title: 'Healing Frequencies', artist: '432 Hz Music', youtubeId: 'cLoytewvn0g' },
    { title: 'Guided Relaxation', artist: 'Meditation', youtubeId: 'ihO02wUzgkc' },
    { title: 'Alpha Waves', artist: 'Binaural Beats', youtubeId: 'WPni755-Krg' },
    { title: 'Stress Relief Music', artist: 'Relaxing Vibes', youtubeId: '1ZYbU82GVz4' },
    { title: 'Ambient Soundscape', artist: 'Brian Eno', youtubeId: 'vNwYtllyt3Q' },
    { title: 'Solfeggio Frequencies', artist: 'Healing Music', youtubeId: 'OjetvUARP9E' },
    { title: 'Crystal Bowl Meditation', artist: 'Sound Healing', youtubeId: 'V7yPFjB95yI' },
    { title: 'Peaceful Harp', artist: 'Celtic Music', youtubeId: 'Qiuo2N05ZpA' }
  ],
  
  stressed: [
    { title: 'Spa Music', artist: 'Meditation Relax Music', youtubeId: '1ZYbU82GVz4' },
    { title: 'Peaceful Piano', artist: 'Relaxing Music', youtubeId: 'lTRiuFIWV54' },
    { title: 'Ocean Waves', artist: 'Nature Sounds', youtubeId: 'bn9F19Hi1Lk' },
    { title: 'Gymnopédie No.1', artist: 'Erik Satie', youtubeId: 'S-Xm7s9eGxU' },
    { title: 'Massage Therapy Music', artist: 'Spa Music', youtubeId: 'bX6hMKGJLpg' },
    { title: 'Stress Relief Meditation', artist: 'Meditation Music', youtubeId: '2OEL4P1Rz04' },
    { title: 'Calm Piano & Strings', artist: 'Classical Music', youtubeId: 'V3fK8K0o5NM' },
    { title: 'Mountain Stream', artist: 'Nature Sounds', youtubeId: 'PWeKUzCF0wI' },
    { title: 'Wind Chimes', artist: 'Ambient Sounds', youtubeId: 'ZJKXZ6bMWBA' },
    { title: 'Japanese Garden', artist: 'Asian Meditation', youtubeId: 'Kd79-5rLwzI' },
    { title: 'Soft Guitar', artist: 'Acoustic Relaxation', youtubeId: '6OFIRf1fqVM' },
    { title: 'Floating', artist: 'Ambient Music', youtubeId: 'UDhw8xzJhfI' },
    { title: 'Waterfall Sounds', artist: 'Nature', youtubeId: 'dme8zJk86Fs' },
    { title: 'Bird Songs', artist: 'Nature Sounds', youtubeId: 'M15CF2FNwmM' },
    { title: 'Deep Breathing Music', artist: 'Relaxation', youtubeId: 'rQ5SqAwdIrc' },
    { title: 'Sunset Meditation', artist: 'Calm Music', youtubeId: 'QNcgHC3qOA0' },
    { title: 'Lotus Flower', artist: 'Zen Music', youtubeId: 'oyDJEp1OdT0' },
    { title: 'Dreamscape', artist: 'Ambient Soundscape', youtubeId: 'rSoJALW5q2o' },
    { title: 'Reiki Healing Music', artist: 'Energy Healing', youtubeId: 'nt3p65gRlg0' },
    { title: 'Theta Waves', artist: 'Binaural Beats', youtubeId: '2jeMb7ylA3M' }
  ],
  
  angry: [
    { title: 'Killing in the Name', artist: 'Rage Against the Machine', youtubeId: 'bWXazVhlyxQ' },
    { title: 'Break Stuff', artist: 'Limp Bizkit', youtubeId: 'ZpUYjpKg9KY' },
    { title: 'In the End', artist: 'Linkin Park', youtubeId: 'eVTXPUF4Oz4' },
    { title: 'The Pretender', artist: 'Foo Fighters', youtubeId: 'SBjQ9tuuTJQ' },
    { title: 'Numb', artist: 'Linkin Park', youtubeId: 'kXYiU_JCYtU' },
    { title: 'Given Up', artist: 'Linkin Park', youtubeId: '0xyxtzD54rM' },
    { title: 'Down with the Sickness', artist: 'Disturbed', youtubeId: '09LTT0xwdfw' },
    { title: 'Bodies', artist: 'Drowning Pool', youtubeId: '04F4xlWSFh0' },
    { title: 'Last Resort', artist: 'Papa Roach', youtubeId: 'j0lSpNtjPM8' },
    { title: 'Psychosocial', artist: 'Slipknot', youtubeId: '5abamRO41fE' },
    { title: 'Chop Suey!', artist: 'System of a Down', youtubeId: 'CSvFpBOe8eY' },
    { title: 'Toxicity', artist: 'System of a Down', youtubeId: 'iywaBOMvYLI' },
    { title: 'One Step Closer', artist: 'Linkin Park', youtubeId: '4qlCC1GOwFw' },
    { title: 'Enter Sandman', artist: 'Metallica', youtubeId: 'CD-E-LDc384' },
    { title: 'Master of Puppets', artist: 'Metallica', youtubeId: 'xnKhsTXoKCI' },
    { title: 'Bulls on Parade', artist: 'Rage Against the Machine', youtubeId: '3L4YrGaR8E4' },
    { title: 'Stupify', artist: 'Disturbed', youtubeId: 'jqLY96_zezc' },
    { title: 'Headstrong', artist: 'Trapt', youtubeId: 'HTvu1n9hRU0' },
    { title: 'Before I Forget', artist: 'Slipknot', youtubeId: 'qw2LU1yS7aw' },
    { title: 'Blow Me Away', artist: 'Breaking Benjamin', youtubeId: 'GoZbxtFL3NI' }
  ],
  
  lonely: [
    { title: "You've Got a Friend", artist: 'Carole King', youtubeId: 'BeOu_D6tHAw' },
    { title: 'Lean on Me', artist: 'Bill Withers', youtubeId: 'fOZ-MySzAac' },
    { title: 'Bridge Over Troubled Water', artist: 'Simon & Garfunkel', youtubeId: '4G-YQA_bsOU' },
    { title: 'True Colors', artist: 'Cyndi Lauper', youtubeId: 'LPn0KFlbqX8' },
    { title: 'With a Little Help from My Friends', artist: 'The Beatles', youtubeId: '0C58ttB2-Qg' },
    { title: 'Stand by Me', artist: 'Ben E. King', youtubeId: 'hwZNL7QVJjE' },
    { title: 'I\'ll Be There', artist: 'The Jackson 5', youtubeId: 'y7kj6hEP6GY' },
    { title: 'You Are Not Alone', artist: 'Michael Jackson', youtubeId: 'pAyKJAtDNCw' },
    { title: 'Lean On', artist: 'Major Lazer & DJ Snake', youtubeId: 'YqeW9_5kURI' },
    { title: 'Feeling Good', artist: 'Nina Simone', youtubeId: 'D5Y11hwjMNs' },
    { title: 'Don\'t Give Up', artist: 'Peter Gabriel & Kate Bush', youtubeId: 'VjEq-r2agqc' },
    { title: 'Unwritten', artist: 'Natasha Bedingfield', youtubeId: 'b7k0a5hYnSI' },
    { title: 'We\'re All in This Together', artist: 'High School Musical', youtubeId: 'GB-Ny3kkmBQ' },
    { title: 'Belong', artist: 'Cary Brothers', youtubeId: 'CdgIJZwT8eM' },
    { title: 'Not Alone', artist: 'Linkin Park', youtubeId: 'x8w95T4sCuY' },
    { title: 'Together', artist: 'For King & Country', youtubeId: 'rDIBr-bGnwY' },
    { title: 'Home', artist: 'Phillip Phillips', youtubeId: 'HoRknxC13V' },
    { title: 'Reach Out', artist: 'Four Tops', youtubeId: 'lxKCP97fGFU' },
    { title: 'Friend Like Me', artist: 'Aladdin', youtubeId: '99Op1TaXmCw' },
    { title: 'We Are Family', artist: 'Sister Sledge', youtubeId: 'uyGY2NfYpeE' }
  ],
  
  motivated: [
    { title: 'Lose Yourself', artist: 'Eminem', youtubeId: '_Yhyp-_hX2s' },
    { title: 'Eye of the Tiger', artist: 'Survivor', youtubeId: 'btPJPFnesV4' },
    { title: 'Remember the Name', artist: 'Fort Minor', youtubeId: 'VDvr08sCPOc' },
    { title: 'Hall of Fame', artist: 'The Script', youtubeId: 'mk48xRzuNvA' },
    { title: 'Till I Collapse', artist: 'Eminem', youtubeId: 'ytQ5CYE1VZw' },
    { title: 'Can\'t Hold Us', artist: 'Macklemore', youtubeId: '2zNSgSzhBfM' },
    { title: 'Gonna Fly Now', artist: 'Bill Conti', youtubeId: 'ioE_O7Lm0I4' },
    { title: 'The Phoenix', artist: 'Fall Out Boy', youtubeId: 'yKOlBZJ7Izs' },
    { title: 'Champion', artist: 'Fall Out Boy', youtubeId: 'cDSoUC_FqKw' },
    { title: 'Centuries', artist: 'Fall Out Boy', youtubeId: 'LBr7kECsjcQ' },
    { title: 'Not Afraid', artist: 'Eminem', youtubeId: 'j5-yKhDd64s' },
    { title: 'Uprising', artist: 'Muse', youtubeId: 'w8KQmps-Sog' },
    { title: 'Go', artist: 'The Chemical Brothers', youtubeId: 'LO2RPDZkY88' },
    { title: 'Don\'t Stop Believin\'', artist: 'Journey', youtubeId: '1k8craCGpgs' },
    { title: 'We Are the Champions', artist: 'Queen', youtubeId: '04854XqcfCY' },
    { title: 'It\'s My Life', artist: 'Bon Jovi', youtubeId: 'vx2u5uUu3DE' },
    { title: 'One Moment in Time', artist: 'Whitney Houston', youtubeId: 'AqwgALOj30I' },
    { title: 'Ain\'t No Mountain High Enough', artist: 'Marvin Gaye', youtubeId: 'Xz-UvQYAmbg' },
    { title: 'Rise', artist: 'Katy Perry', youtubeId: 'hdw1uKiTI5c' },
    { title: 'Victorious', artist: 'Panic! At The Disco', youtubeId: 'AUChk0lxF44' }
  ],
  
  loved: [
    { title: 'Perfect', artist: 'Ed Sheeran', youtubeId: '2Vv-BfVoq4g' },
    { title: 'All of Me', artist: 'John Legend', youtubeId: '450p7goxZqg' },
    { title: 'Thinking Out Loud', artist: 'Ed Sheeran', youtubeId: 'lp-EO5I60KA' },
    { title: 'Just the Way You Are', artist: 'Bruno Mars', youtubeId: 'LjhCEhWiKXk' },
    { title: 'A Thousand Years', artist: 'Christina Perri', youtubeId: 'rtOvBOTyX00' },
    { title: 'Make You Feel My Love', artist: 'Adele', youtubeId: '0put0_a--Ng' },
    { title: 'You Are the Reason', artist: 'Calum Scott', youtubeId: 'ByfFurjQDb0' },
    { title: 'Say You Won\'t Let Go', artist: 'James Arthur', youtubeId: '0yW7w8F2TVA' },
    { title: 'Marry You', artist: 'Bruno Mars', youtubeId: 'Dlz8DVn1Mjc' },
    { title: 'Can\'t Help Falling in Love', artist: 'Elvis Presley', youtubeId: 'vGJTaP6anOU' },
    { title: 'At Last', artist: 'Etta James', youtubeId: 'S-cbOl96RFM' },
    { title: 'Wonderful Tonight', artist: 'Eric Clapton', youtubeId: 'kHue-4gIfq8' },
    { title: 'Your Song', artist: 'Elton John', youtubeId: 'mTa8U0Wa0q8' },
    { title: 'Endless Love', artist: 'Diana Ross & Lionel Richie', youtubeId: '8r-e2NDSTuU' },
    { title: 'Unchained Melody', artist: 'The Righteous Brothers', youtubeId: 'qiiyq2xrSI0' },
    { title: 'You\'re Still the One', artist: 'Shania Twain', youtubeId: 'KNZH-emehxA' },
    { title: 'Because You Loved Me', artist: 'Celine Dion', youtubeId: 'CKLQCyMrRpE' },
    { title: 'Power of Love', artist: 'Celine Dion', youtubeId: 'Y8HOfcYWZoo' },
    { title: 'Crazy Love', artist: 'Van Morrison', youtubeId: 'vVRDYTyByVE' },
    { title: 'I Choose You', artist: 'Sara Bareilles', youtubeId: 'U4Q52gJvSNw' }
  ],
  
  hopeful: [
    { title: 'Here Comes the Sun', artist: 'The Beatles', youtubeId: 'KQetemT1sWc' },
    { title: 'Better Days', artist: 'OneRepublic', youtubeId: 'N6nZ6-R0fWE' },
    { title: 'Unwritten', artist: 'Natasha Bedingfield', youtubeId: 'b7k0a5hYnSI' },
    { title: 'Beautiful Day', artist: 'U2', youtubeId: 'co6WMzDOh1o' },
    { title: 'Rise Up', artist: 'Andra Day', youtubeId: 'lwgr_IMeEgA' },
    { title: 'Fight Song', artist: 'Rachel Platten', youtubeId: 'xo1VInw-SKc' },
    { title: 'Brand New Day', artist: 'Sting', youtubeId: 'H5LpdDQExng' },
    { title: 'Tomorrow', artist: 'Annie', youtubeId: '5PzL8fgoxT0' },
    { title: 'A Sky Full of Stars', artist: 'Coldplay', youtubeId: 'VPRjCeoBqrI' },
    { title: 'Paradise', artist: 'Coldplay', youtubeId: '1G4isv_Fylg' },
    { title: 'Viva La Vida', artist: 'Coldplay', youtubeId: 'dvgZkm1xWPE' },
    { title: 'Firework', artist: 'Katy Perry', youtubeId: 'QGJuMBdaqIw' },
    { title: 'I Believe I Can Fly', artist: 'R. Kelly', youtubeId: 'GIQn8pab8Vc' },
    { title: 'Waiting for the World to Change', artist: 'John Mayer', youtubeId: '0E1bNmyPWww' },
    { title: 'Alive', artist: 'Sia', youtubeId: 't2NgsJrrAyM' },
    { title: 'Wherever You Will Go', artist: 'The Calling', youtubeId: 'iAP9AF6DCu4' },
    { title: 'Next to Me', artist: 'Imagine Dragons', youtubeId: 'wZgVOa-_4N4' },
    { title: 'On Top of the World', artist: 'Imagine Dragons', youtubeId: 'w5tWYmIOWGk' },
    { title: 'Nothing\'s Gonna Stop Us Now', artist: 'Starship', youtubeId: '3wxyN3z9PL4' },
    { title: 'The Climb', artist: 'Miley Cyrus', youtubeId: 'NG2zyeVRcbs' }
  ],
  
  proud: [
    { title: 'We Are the Champions', artist: 'Queen', youtubeId: '04854XqcfCY' },
    { title: 'Hall of Fame', artist: 'The Script', youtubeId: 'mk48xRzuNvA' },
    { title: 'Victory', artist: 'Puff Daddy', youtubeId: 'VHEUFzwIT54' },
    { title: 'All I Do Is Win', artist: 'DJ Khaled', youtubeId: 'GGXzlRoNtHU' },
    { title: 'Started From the Bottom', artist: 'Drake', youtubeId: 'RubBzkZzpUA' },
    { title: 'This Is Me', artist: 'Keala Settle', youtubeId: 'XLFEvHWD_NE' },
    { title: 'High Hopes', artist: 'Panic! At The Disco', youtubeId: 'IPXIgEAGe4U' },
    { title: 'On Top of the World', artist: 'Imagine Dragons', youtubeId: 'w5tWYmIOWGk' },
    { title: 'Glorious', artist: 'Macklemore ft. Skylar Grey', youtubeId: '7OrLroFa0AI' },
    { title: 'Can\'t Stop', artist: 'Red Hot Chili Peppers', youtubeId: 'BfOdWSiyWoc' },
    { title: 'Stronger', artist: 'Kelly Clarkson', youtubeId: 'Xn676-fLq7I' },
    { title: 'I\'m Still Standing', artist: 'Elton John', youtubeId: 'ZHwVBirqD2s' },
    { title: 'Celebration', artist: 'Kool & the Gang', youtubeId: '3GwjfUFyY6M' },
    { title: 'Happy', artist: 'Pharrell Williams', youtubeId: 'ZbZSe6N_BXs' },
    { title: 'Flying Without Wings', artist: 'Westlife', youtubeId: 'ByhYKgNPLNQ' },
    { title: 'I Gotta Feeling', artist: 'Black Eyed Peas', youtubeId: 'uSD4vsh1zDA' },
    { title: 'The Time of My Life', artist: 'Black Eyed Peas', youtubeId: 'bsUWK-fixiA' },
    { title: 'Best Day of My Life', artist: 'American Authors', youtubeId: 'Y66j_BUCBMY' },
    { title: 'Radioactive', artist: 'Imagine Dragons', youtubeId: 'ktvTqknDobU' },
    { title: 'Thunder', artist: 'Imagine Dragons', youtubeId: 'fKopy74weus' }
  ],
  
  // Additional emotions
  fearful: [
    { title: 'Breathe', artist: 'Télépopmusik', youtubeId: 'vyut3GyQtn0' },
    { title: 'Safe and Sound', artist: 'Capital Cities', youtubeId: '47dtFZ8CFo8' },
    { title: 'Shake It Out', artist: 'Florence + The Machine', youtubeId: 'WbN0nX61rIs' },
    { title: 'Dog Days Are Over', artist: 'Florence + The Machine', youtubeId: 'iWOyfLBYtuU' },
    { title: 'It\'s Gonna Be Okay', artist: 'Shania Twain', youtubeId: 'UzX59KPxgMY' },
    { title: 'Hold On', artist: 'Wilson Phillips', youtubeId: 'uIbXvaE39wM' },
    { title: 'I\'m Not Afraid', artist: 'Eminem', youtubeId: 'j5-yKhDd64s' },
    { title: 'Brave', artist: 'Sara Bareilles', youtubeId: 'QUQsqBqxoR4' },
    { title: 'Titanium', artist: 'David Guetta ft. Sia', youtubeId: 'JRfuAukYTKg' },
    { title: 'Survivor', artist: 'Destiny\'s Child', youtubeId: 'Wmc8bQoL-J0' }
  ],
  
  guilty: [
    { title: 'Apologize', artist: 'OneRepublic', youtubeId: 'ZSM3w1v-A_Y' },
    { title: 'Sorry', artist: 'Justin Bieber', youtubeId: 'fRh_vgS2dFE' },
    { title: 'The Reason', artist: 'Hoobastank', youtubeId: 'fV4DiAyExN0' },
    { title: 'Jar of Hearts', artist: 'Christina Perri', youtubeId: '8v_4O44sfjM' },
    { title: 'How to Save a Life', artist: 'The Fray', youtubeId: 'cjVQ36NhbMk' },
    { title: 'Everybody Hurts', artist: 'R.E.M.', youtubeId: '5rOiW_xY-kc' },
    { title: 'Hurt', artist: 'Christina Aguilera', youtubeId: 'HivpAlSdVxg' },
    { title: 'Love the Way You Lie', artist: 'Eminem ft. Rihanna', youtubeId: 'uelHwf8o7_U' },
    { title: 'Back to December', artist: 'Taylor Swift', youtubeId: 'QUwxKWT6m7U' },
    { title: 'Because of You', artist: 'Kelly Clarkson', youtubeId: 'Ra-Om7UMSJc' }
  ],
  
  disappointed: [
    { title: 'Somebody That I Used to Know', artist: 'Gotye', youtubeId: '8UVNT4wvIGY' },
    { title: 'When I Was Your Man', artist: 'Bruno Mars', youtubeId: 'ekzHIouo8Q4' },
    { title: 'We Are Never Getting Back Together', artist: 'Taylor Swift', youtubeId: 'WA4iX5D9Z64' },
    { title: 'Since U Been Gone', artist: 'Kelly Clarkson', youtubeId: 'R7UrFYvl5TE' },
    { title: 'Torn', artist: 'Natalie Imbruglia', youtubeId: 'VV1XWJN3nJo' },
    { title: 'Boulevard of Broken Dreams', artist: 'Green Day', youtubeId: 'Soa3gO7tL-c' },
    { title: 'Cry Me a River', artist: 'Justin Timberlake', youtubeId: 'DksSPZTZES0' },
    { title: 'Breakeven', artist: 'The Script', youtubeId: 'MzCLLHscMOw' },
    { title: 'The Man Who Can\'t Be Moved', artist: 'The Script', youtubeId: 'gS9o1FAszdk' },
    { title: 'Don\'t Speak', artist: 'No Doubt', youtubeId: 'TR3Vdo5etCQ' }
  ],
  
  confused: [
    { title: 'Losing My Religion', artist: 'R.E.M.', youtubeId: 'xwtdhWltSIg' },
    { title: 'Crazy', artist: 'Gnarls Barkley', youtubeId: 'bd2B6SjMh_w' },
    { title: 'Where Is My Mind?', artist: 'Pixies', youtubeId: '49FB9hhoO6c' },
    { title: 'Iris', artist: 'Goo Goo Dolls', youtubeId: 'NdYWuo9OFAw' },
    { title: 'Wonderwall', artist: 'Oasis', youtubeId: 'bx1Bh8ZvH84' },
    { title: 'Teenage Dirtbag', artist: 'Wheatus', youtubeId: 'FC3y9llDXuM' },
    { title: 'Basket Case', artist: 'Green Day', youtubeId: 'NUTGr5t3MoY' },
    { title: 'Semi-Charmed Life', artist: 'Third Eye Blind', youtubeId: 'beINamVRGy4' },
    { title: 'Mr. Jones', artist: 'Counting Crows', youtubeId: '-oqAU5VxFWs' },
    { title: 'Black Hole Sun', artist: 'Soundgarden', youtubeId: '3mbBbFH9fAg' }
  ],
  
  nostalgic: [
    { title: 'Wonderwall', artist: 'Oasis', youtubeId: 'bx1Bh8ZvH84' },
    { title: 'Summer of \'69', artist: 'Bryan Adams', youtubeId: 'eFjjO_lhf9c' },
    { title: 'Sweet Child O\' Mine', artist: 'Guns N\' Roses', youtubeId: '1w7OgIMMRc4' },
    { title: 'November Rain', artist: 'Guns N\' Roses', youtubeId: '8SbUC-UaAxE' },
    { title: 'Bohemian Rhapsody', artist: 'Queen', youtubeId: 'fJ9rUzIMcZQ' },
    { title: 'Hotel California', artist: 'Eagles', youtubeId: 'BciS5krYL80' },
    { title: 'Stairway to Heaven', artist: 'Led Zeppelin', youtubeId: 'QkF3oxziUI4' },
    { title: 'Yesterday', artist: 'The Beatles', youtubeId: 'wXTJBr9tt8Q' },
    { title: 'Imagine', artist: 'John Lennon', youtubeId: 'YkgkThdzX-8' },
    { title: 'Take On Me', artist: 'a-ha', youtubeId: 'djV11Xbc914' },
    { title: 'Don\'t Stop Believin\'', artist: 'Journey', youtubeId: '1k8craCGpgs' },
    { title: 'Livin\' on a Prayer', artist: 'Bon Jovi', youtubeId: 'lDK9QqIzhwk' },
    { title: 'Africa', artist: 'Toto', youtubeId: 'FTQbiNvZqaY' },
    { title: 'Every Breath You Take', artist: 'The Police', youtubeId: 'OMOGaugKpzs' },
    { title: 'With or Without You', artist: 'U2', youtubeId: 'XmSdTa9kaiQ' }
  ],
  
  bored: [
    { title: 'Adventure of a Lifetime', artist: 'Coldplay', youtubeId: 'QtXby3twMmI' },
    { title: 'Wake Me Up', artist: 'Avicii', youtubeId: 'IcrbM1l_BoI' },
    { title: 'Pump It Up', artist: 'Endor', youtubeId: 'BfnjX88Va4Y' },
    { title: 'Levels', artist: 'Avicii', youtubeId: '_ovdm2yX4MA' },
    { title: 'Animals', artist: 'Martin Garrix', youtubeId: 'gCYcHz2k5x0' },
    { title: 'Rather Be', artist: 'Clean Bandit', youtubeId: 'm-M1AtrxztU' },
    { title: 'This Is What You Came For', artist: 'Calvin Harris', youtubeId: 'kOkQ4T5WO9E' },
    { title: 'One Kiss', artist: 'Calvin Harris & Dua Lipa', youtubeId: 'DkeiKbqa02g' },
    { title: 'Blinding Lights', artist: 'The Weeknd', youtubeId: '4NRXx6U8ABQ' },
    { title: 'Starboy', artist: 'The Weeknd', youtubeId: '34Na4j8AVgA' }
  ]
};

// Continuation in next file due to size...